
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adalberto
 */
public class Ejercicio6 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio6
     */
    public Ejercicio6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtTamaño = new javax.swing.JTextField();
        txtPalabras = new javax.swing.JTextField();
        cmdTotal = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtColor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("periodico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setText("digite Numeros de Palabras: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 70, 150, -1));

        jLabel3.setText("digite tamaño :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setText("digite Numero de Colores :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, -1));

        txtTamaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamañoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 110, -1));

        txtPalabras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabrasKeyTyped(evt);
            }
        });
        getContentPane().add(txtPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 110, -1));

        cmdTotal.setText("total pagar");
        cmdTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTotalActionPerformed(evt);
            }
        });
        getContentPane().add(cmdTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTotalActionPerformed
       float tamaño, color, palabras, total;
        String sumatoria;
    
     if(txtPalabras.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite el cantidad de palabras","error", JOptionPane.ERROR_MESSAGE);
         txtPalabras.requestFocusInWindow();
         txtPalabras.selectAll();
     }
     else if(txtTamaño.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el tamaño","error", JOptionPane.ERROR_MESSAGE);  
        txtTamaño.requestFocusInWindow();
        txtTamaño.selectAll();
     }  
     else if(txtColor.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el número de colores","error", JOptionPane.ERROR_MESSAGE);  
        txtColor.requestFocusInWindow(); 
         txtColor.selectAll();    
     }
     else{   
     palabras=Integer.parseInt(txtPalabras.getText());
     tamaño=Float.parseFloat(txtTamaño.getText());
     color=Integer.parseInt(txtColor.getText());
         
    total=((palabras*20000)+(tamaño*15000)+(color*25000));   
    
    sumatoria=String.valueOf(total);
    txtTotal.setText(sumatoria);
    
    }
    }//GEN-LAST:event_cmdTotalActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
     txtPalabras.setText("");
     txtTamaño.setText("");
     txtColor.setText("");
     txtTotal.setText("");;

     txtPalabras.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtPalabrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabrasKeyTyped
       char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtPalabrasKeyTyped

    private void txtTamañoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamañoKeyTyped
       char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtTamañoKeyTyped

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
       char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtColorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtPalabras;
    private javax.swing.JTextField txtTamaño;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
